# Chapter 5 - Basic Math and Statistics
## Segment 1 - Using NumPy to perform arithmetic operations on data

In [0]:
import numpy as np
from numpy.random import randn

In [0]:
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [4]:
a = np.array(range(1,7))
a

array([1, 2, 3, 4, 5, 6])

In [5]:
b = np.array([[10,20,20],[40,50,60]])

b

array([[10, 20, 20],
       [40, 50, 60]])

### Creating arrays via assignment

In [7]:
np.random.seed(25)
c=36*np.random.randn(6)
c

array([  8.21783123,  36.96805091, -30.22505456, -21.28253464,
       -34.44797868,  -8.003725  ])

In [9]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

## Performing arthimetic on arrays

### Multiplying matrices and basic linear algebra